### ISSUE TITLE
If collected knowledge of a repository is not present, visualization should not start at all

### ISSUE THREAD

**Issue by pacospace** [thoth-station/mi#143]
**Describe the bug**

**To Reproduce**
1. Choose a repo that you never used to collect knowledge.
2. `run PYTHONPATH=. pipenv run python3 srcopsmetrics/cli.py --repository <repository> -v -l`

**Expected behavior**
Receive immediately a Warning and process stop suggesting to collect the knowledge about that repo first, or directly running the collection of knowledge before running processing of data which do not exist and creating all empty repos and files.

**Screenshots**
```
INFO:srcopsmetrics.github_knowledge:Overall repositories found: 1
INFO:srcopsmetrics.storage:Loading knowledge locally
INFO:srcopsmetrics.storage:No previous knowledge of type PullRequest found
INFO:srcopsmetrics.storage:Loading knowledge locally
INFO:srcopsmetrics.storage:No previous knowledge of type Issue found
INFO:srcopsmetrics.utils:No repo identified, creating new directory at srcopsmetrics/processed/aiidateam/aiida-core
INFO:srcopsmetrics.storage:Loading knowledge locally
INFO:srcopsmetrics.storage:No previous knowledge of type Processed Knowledge found
INFO:srcopsmetrics.storage:Saving knowledge file process_issues_creators.json of size 0
INFO:srcopsmetrics.storage:Saved locally at srcopsmetrics/processed/aiidateam/aiida-core/process_issues_creators.json
INFO:srcopsmetrics.storage:Loading knowledge locally
INFO:srcopsmetrics.storage:Found previous knowledge for None with 0 entities of type Processed Knowledge
INFO:srcopsmetrics.storage:Saving knowledge file process_issues_creators.json of size 0
INFO:srcopsmetrics.storage:Saved locally at srcopsmetrics/processed/aiidateam/aiida-core/process_issues_creators.json
INFO:srcopsmetrics.storage:Loading knowledge locally
INFO:srcopsmetrics.storage:No previous knowledge of type Processed Knowledge found
INFO:srcopsmetrics.storage:Saving knowledge file overall_issues_status.json of size 2
INFO:srcopsmetrics.storage:Saved locally at srcopsmetrics/processed/aiidateam/aiida-core/overall_issues_status.json
INFO:srcopsmetrics.storage:Loading knowledge locally
INFO:srcopsmetrics.storage:No previous knowledge of type Processed Knowledge found
INFO:srcopsmetrics.storage:Saving knowledge file overall_prs_status.json of size 3
INFO:srcopsmetrics.storage:Saved locally at srcopsmetrics/processed/aiidateam/aiida-core/overall_prs_status.json
Traceback (most recent call last):
  File "srcopsmetrics/cli.py", line 148, in <module>
    cli()
  File "/home/fmurdaca/.local/share/virtualenvs/mi-_yZ92-Ga/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/fmurdaca/.local/share/virtualenvs/mi-_yZ92-Ga/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/fmurdaca/.local/share/virtualenvs/mi-_yZ92-Ga/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/fmurdaca/.local/share/virtualenvs/mi-_yZ92-Ga/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "srcopsmetrics/cli.py", line 133, in cli
    visualize_project_results(project=project, is_local=is_local)
  File "/home/fmurdaca/work/aicoe/mi/srcopsmetrics/bot_knowledge.py", line 79, in visualize_project_results
    report.generate_health_report()
  File "/home/fmurdaca/work/aicoe/mi/srcopsmetrics/report.py", line 122, in generate_health_report
    figure=self.in_time_section()
  File "/home/fmurdaca/work/aicoe/mi/srcopsmetrics/report.py", line 177, in in_time_section
    fig.append_trace(self.viz.scatter_ttci_in_time(), row=1, col=1)
  File "/home/fmurdaca/work/aicoe/mi/srcopsmetrics/visualization.py", line 661, in scatter_ttci_in_time
    issues_created_dts = project_issues_data["created_dts"]
KeyError: 'created_dts'
```

**Comment by xtuchyna** [comment]
Visualizations not used anymore (see #180 ), therefore closing issue.
