### ISSUE TITLE
Commit analysis fails

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/mi#318]
**Describe the bug**
```
INFO:srcopsmetrics.github_knowledge:Overall repositories found: 1
INFO:srcopsmetrics.bot_knowledge:######################## Analysing AICoE/prometheus-anomaly-detector ########################

INFO:srcopsmetrics.utils:No repo identified, creating new directory at /opt/app-root/src/srcopsmetrics/bot_knowledge/AICoE/prometheus-anomaly-detector
INFO:srcopsmetrics.bot_knowledge:########################
INFO:srcopsmetrics.bot_knowledge:Detected entities:
CodeFrequency # Commit # DependencyUpdate # Fork # Issue # KebechetUpdateManager # PullRequest # PullRequestDiscussion # ReadMe # Release # Stargazer
INFO:srcopsmetrics.bot_knowledge:########################

....

INFO:srcopsmetrics.bot_knowledge:Commit inspection
INFO:srcopsmetrics.entities.tools.storage:Loading knowledge from Ceph
INFO:srcopsmetrics.entities.interface:No previous knowledge of type Commit found
INFO:srcopsmetrics.iterator:-------------Commit Analysis-------------
INFO:srcopsmetrics.iterator:Analysing Commit no. 1/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 2/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 3/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 4/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 5/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 6/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 7/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 8/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 9/138
INFO:srcopsmetrics.iterator:[ API requests remaining: 3614 ]
INFO:srcopsmetrics.iterator:Analysing Commit no. 10/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 11/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 12/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 13/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 14/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 15/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 16/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 17/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 18/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 19/138
INFO:srcopsmetrics.iterator:[ API requests remaining: 3526 ]
INFO:srcopsmetrics.iterator:Analysing Commit no. 20/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 21/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 22/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 23/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 24/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 25/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 26/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 27/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 28/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 29/138
INFO:srcopsmetrics.iterator:[ API requests remaining: 3400 ]
INFO:srcopsmetrics.iterator:Analysing Commit no. 30/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 31/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 32/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 33/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 34/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 35/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 36/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 37/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 38/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 39/138
INFO:srcopsmetrics.iterator:[ API requests remaining: 3266 ]
INFO:srcopsmetrics.iterator:Analysing Commit no. 40/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 41/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 42/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 43/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 44/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 45/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 46/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 47/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 48/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 49/138
INFO:srcopsmetrics.iterator:[ API requests remaining: 3106 ]
INFO:srcopsmetrics.iterator:Analysing Commit no. 50/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 51/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 52/138
INFO:srcopsmetrics.iterator:Analysing Commit no. 53/138
INFO:srcopsmetrics.iterator:Problem occured, checking knowledge consistency
INFO:srcopsmetrics.iterator:Knowledge inconsistent, restoring cached knowledge
INFO:srcopsmetrics.iterator:Cached knowledge could not be saved
Traceback (most recent call last):
  File "/opt/app-root/src/srcopsmetrics/iterator.py", line 95, in run
    self.entity.store(entity)
  File "/opt/app-root/src/srcopsmetrics/entities/commit.py", line 51, in store
    pull_request_id = commit.get_pulls()[0].number if commit.get_pulls().totalCount != 0 else None
  File "/opt/app-root/lib64/python3.8/site-packages/github/PaginatedList.py", line 48, in __getitem__
    self.__fetchToIndex(index)
  File "/opt/app-root/lib64/python3.8/site-packages/github/PaginatedList.py", line 64, in __fetchToIndex
    self._grow()
  File "/opt/app-root/lib64/python3.8/site-packages/github/PaginatedList.py", line 67, in _grow
    newElements = self._fetchNextPage()
  File "/opt/app-root/lib64/python3.8/site-packages/github/PaginatedList.py", line 199, in _fetchNextPage
    headers, data = self.__requester.requestJsonAndCheck(
  File "/opt/app-root/lib64/python3.8/site-packages/github/Requester.py", line 315, in requestJsonAndCheck
    return self.__check(
  File "/opt/app-root/lib64/python3.8/site-packages/github/Requester.py", line 340, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.RateLimitExceededException: 403 {"documentation_url": "https://docs.github.com/en/free-pro-team@latest/rest/overview/resources-in-the-rest-api#abuse-rate-limits", "message": "You have triggered an abuse detection mechanism. Please wait a few minutes before you try again."}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/app-root/src/srcopsmetrics/iterator.py", line 100, in run
    self.entity.entities_schema()(self.entity.stored_entities)
  File "/opt/app-root/lib64/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/opt/app-root/lib64/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/opt/app-root/lib64/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: expected str for dictionary value @ data['09acce292e18dff70a50449bf4bdf228cf75b5d5']['patch']['notebooks/metrics/prometheus-route-aiops-prod-prometheus-predict.cloud.paas.psi.redhat.com/request_duration_seconds_count.csv']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "srcopsmetrics/cli.py", line 140, in <module>
    cli()
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "srcopsmetrics/cli.py", line 122, in cli
    analyse_projects(projects=tupled_repos, is_local=is_local, entities=entities_args)
  File "/opt/app-root/src/srcopsmetrics/bot_knowledge.py", line 89, in analyse_projects
    github_knowledge.analyse_entity(
  File "/opt/app-root/src/srcopsmetrics/github_knowledge.py", line 187, in analyse_entity
    analysis.run()
  File "/opt/app-root/src/srcopsmetrics/iterator.py", line 104, in run
    self.entity.entities_schema()(backup)
  File "/opt/app-root/lib64/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/opt/app-root/lib64/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/opt/app-root/lib64/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: expected str for dictionary value @ data['09acce292e18dff70a50449bf4bdf228cf75b5d5']['patch']['notebooks/metrics/prometheus-route-aiops-prod-prometheus-predict.cloud.paas.psi.redhat.com/request_duration_seconds_count.csv']
```

**Comment by xtuchyna** [comment]
Also
```
INFO:srcopsmetrics.github_knowledge:Overall repositories found: 1
INFO:srcopsmetrics.bot_knowledge:######################## Analysing thoth-station/termial-random ########################

INFO:srcopsmetrics.utils:No repo identified, creating new directory at /opt/app-root/src/srcopsmetrics/bot_knowledge/thoth-station/termial-random
INFO:srcopsmetrics.bot_knowledge:########################
INFO:srcopsmetrics.bot_knowledge:Detected entities:
CodeFrequency # Commit # DependencyUpdate # Fork # Issue # KebechetUpdateManager # PullRequest # PullRequestDiscussion # ReadMe # Release # Stargazer
INFO:srcopsmetrics.bot_knowledge:########################
INFO:srcopsmetrics.bot_knowledge:CodeFrequency inspection
INFO:srcopsmetrics.entities.tools.storage:Loading knowledge from Ceph
INFO:srcopsmetrics.entities.interface:No previous knowledge of type CodeFrequency found
INFO:srcopsmetrics.iterator:-------------CodeFrequency Analysis-------------
INFO:srcopsmetrics.iterator:Analysing CodeFrequency no. 1/16
INFO:srcopsmetrics.iterator:Analysing CodeFrequency no. 2/16
INFO:srcopsmetrics.iterator:Analysing CodeFrequency no. 3/16
INFO:srcopsmetrics.iterator:Analysing CodeFrequency no. 4/16
INFO:srcopsmetrics.iterator:Analysing CodeFrequency no. 5/16
INFO:srcopsmetrics.iterator:Analysing CodeFrequency no. 6/16
INFO:srcopsmetrics.iterator:Analysing CodeFrequency no. 7/16
INFO:srcopsmetrics.iterator:Analysing CodeFrequency no. 8/16
INFO:srcopsmetrics.iterator:Analysing CodeFrequency no. 9/16
INFO:srcopsmetrics.iterator:[ API requests remaining: 4845 ]
INFO:srcopsmetrics.iterator:Analysing CodeFrequency no. 10/16
INFO:srcopsmetrics.iterator:Analysing CodeFrequency no. 11/16
INFO:srcopsmetrics.iterator:Analysing CodeFrequency no. 12/16
INFO:srcopsmetrics.iterator:Analysing CodeFrequency no. 13/16
INFO:srcopsmetrics.iterator:Analysing CodeFrequency no. 14/16
INFO:srcopsmetrics.iterator:Analysing CodeFrequency no. 15/16
INFO:srcopsmetrics.iterator:Analysing CodeFrequency no. 16/16
INFO:srcopsmetrics.entities.interface:Knowledge file CodeFrequency.json
INFO:srcopsmetrics.entities.interface:new 16 entities
INFO:srcopsmetrics.entities.interface:(overall 16 entities)
INFO:srcopsmetrics.entities.interface:Saved on CEPH at thoth/data/srcopsmetrics/bot_knowledge/thoth-station/termial-random/CodeFrequency.json
INFO:srcopsmetrics.bot_knowledge:

INFO:srcopsmetrics.bot_knowledge:Commit inspection
INFO:srcopsmetrics.entities.tools.storage:Loading knowledge from Ceph
INFO:srcopsmetrics.entities.interface:No previous knowledge of type Commit found
INFO:srcopsmetrics.iterator:-------------Commit Analysis-------------
INFO:srcopsmetrics.iterator:Analysing Commit no. 1/5
INFO:srcopsmetrics.iterator:Analysing Commit no. 2/5
INFO:srcopsmetrics.iterator:Analysing Commit no. 3/5
INFO:srcopsmetrics.iterator:Analysing Commit no. 4/5
INFO:srcopsmetrics.iterator:Analysing Commit no. 5/5
INFO:srcopsmetrics.iterator:Cached knowledge could not be saved
Traceback (most recent call last):
  File "srcopsmetrics/cli.py", line 140, in <module>
    cli()
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "srcopsmetrics/cli.py", line 122, in cli
    analyse_projects(projects=tupled_repos, is_local=is_local, entities=entities_args)
  File "/opt/app-root/src/srcopsmetrics/bot_knowledge.py", line 89, in analyse_projects
    github_knowledge.analyse_entity(
  File "/opt/app-root/src/srcopsmetrics/github_knowledge.py", line 188, in analyse_entity
    analysis.save_analysed_knowledge()
  File "/opt/app-root/src/srcopsmetrics/iterator.py", line 111, in save_analysed_knowledge
    self.entity.save_knowledge(is_local=self.is_local)
  File "/opt/app-root/src/srcopsmetrics/entities/interface.py", line 114, in save_knowledge
    self.entities_schema()(self.stored_entities)  # check for entities schema
  File "/opt/app-root/lib64/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/opt/app-root/lib64/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/opt/app-root/lib64/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: expected str for dictionary value @ data['21c0f95ce83eeb666d0deba0e3c611300d6ee351']['patch']['fig/distribution.png']
```
