### ISSUE TITLE
When trying to retrieve document, time out happens

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/mi#420]
**Describe the bug**
When trying to retrieve document from ceph (zero cluster, `thoth-test-core`, timeout error is raised).

**To Reproduce**
1. `oc project thoth-test-core`
2. `oc create job --from=cronjob/mi-scheduler-kebechet-analyse mi-keb-analyse-test`
3. look out for logs of recent `mi-analysis-mi...` workflow
4. See that it takes the minute to try and retrieve the doc from ceph, but then it fails due to timeout error.

**Additional information**
See more at:
- https://github.com/thoth-station/thoth-application/blob/d3262b0066cae2ac8aad875a0d8c41f18b13e8bc/mi-scheduler/base/argo-workflows/mi-workflow-template.yaml#L65 (bucket setup)
- https://github.com/thoth-station/thoth-application/blob/d3262b0066cae2ac8aad875a0d8c41f18b13e8bc/mi-scheduler/base/cronjob.yaml#L103 (`storages` setup)

**LOGS**
```
INFO:srcopsmetrics.github_knowledge:Overall repositories found: 1
INFO:srcopsmetrics.bot_knowledge:######################## Analysing thoth-station/thoth-ops ########################

INFO:srcopsmetrics.utils:No repo identified, creating new directory at /opt/app-root/src/srcopsmetrics/bot_knowledge/thoth-station/thoth-ops
INFO:srcopsmetrics.bot_knowledge:########################
INFO:srcopsmetrics.bot_knowledge:Detected entities:
CodeFrequency # Commit # DependencyUpdate # Fork # Issue # KebechetUpdateManager # PullRequest # PullRequestDiscussion # ReadMe # Release # Stargazer
INFO:srcopsmetrics.bot_knowledge:########################
INFO:srcopsmetrics.bot_knowledge:Issue inspection
INFO:srcopsmetrics.utils:No repo identified, creating new directory at /opt/app-root/src/thoth-test-core/thoth-sli-metrics/kebechet-update-manager/bot_knowledge/thoth-station/thoth-ops
INFO:srcopsmetrics.entities.tools.storage:Loading knowledge from Ceph
INFO:srcopsmetrics.iterator:Cached knowledge could not be saved
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/app-root/lib64/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.8/http/client.py", line 1332, in getresponse
    response.begin()
  File "/usr/lib64/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/botocore/httpsession.py", line 323, in send
    urllib_response = conn.urlopen(
  File "/opt/app-root/lib64/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/opt/app-root/lib64/python3.8/site-packages/urllib3/util/retry.py", line 507, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/app-root/lib64/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/opt/app-root/lib64/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/app-root/lib64/python3.8/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/opt/app-root/lib64/python3.8/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: AWSHTTPConnectionPool(host='s3.openshift-storage.svc.cluster.local', port=80): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "srcopsmetrics/cli.py", line 196, in <module>
    cli(auto_envvar_prefix="MI")
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "srcopsmetrics/cli.py", line 159, in cli
    analyse_projects(projects=tupled_repos, is_local=is_local, entities=entities_args)
  File "/opt/app-root/src/srcopsmetrics/bot_knowledge.py", line 89, in analyse_projects
    github_knowledge.analyse_entity(
  File "/opt/app-root/src/srcopsmetrics/github_knowledge.py", line 186, in analyse_entity
    analysis.init_previous_knowledge()
  File "/opt/app-root/src/srcopsmetrics/iterator.py", line 67, in init_previous_knowledge
    self.entity.previous_knowledge = self.entity.load_previous_knowledge(is_local=self.is_local)
  File "/opt/app-root/src/srcopsmetrics/entities/interface.py", line 155, in load_previous_knowledge
    else KnowledgeStorage().load_remotely(self.file_path)
  File "/opt/app-root/src/srcopsmetrics/entities/tools/storage.py", line 157, in load_remotely
    data = self.get_ceph_store().retrieve_document(ceph_filename)
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/storages/ceph.py", line 108, in retrieve_document
    return json.loads(self.retrieve_blob(document_id).decode())
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/storages/ceph.py", line 94, in retrieve_blob
    return self._s3.Object(self.bucket, f"{self.prefix}{object_key}").get()["Body"].read()
  File "/opt/app-root/lib64/python3.8/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/opt/app-root/lib64/python3.8/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/botocore/client.py", line 691, in _make_api_call
    http, parsed_response = self._make_request(
  File "/opt/app-root/lib64/python3.8/site-packages/botocore/client.py", line 711, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/opt/app-root/lib64/python3.8/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/opt/app-root/lib64/python3.8/site-packages/botocore/endpoint.py", line 136, in _send_request
    while self._needs_retry(attempts, operation_model, request_dict,
  File "/opt/app-root/lib64/python3.8/site-packages/botocore/endpoint.py", line 253, in _needs_retry
    responses = self._event_emitter.emit(
  File "/opt/app-root/lib64/python3.8/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/opt/app-root/lib64/python3.8/site-packages/botocore/retryhandler.py", line 250, in __call__
    should_retry = self._should_retry(attempt_number, response,
  File "/opt/app-root/lib64/python3.8/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/opt/app-root/lib64/python3.8/site-packages/botocore/retryhandler.py", line 316, in __call__
    checker_response = checker(attempt_number, response,
  File "/opt/app-root/lib64/python3.8/site-packages/botocore/retryhandler.py", line 222, in __call__
    return self._check_caught_exception(
  File "/opt/app-root/lib64/python3.8/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/opt/app-root/lib64/python3.8/site-packages/botocore/endpoint.py", line 200, in _do_get_response
    http_response = self._send(request)
  File "/opt/app-root/lib64/python3.8/site-packages/botocore/endpoint.py", line 269, in _send
    return self.http_session.send(request)
  File "/opt/app-root/lib64/python3.8/site-packages/botocore/httpsession.py", line 358, in send
    raise ReadTimeoutError(endpoint_url=request.url, error=e)
botocore.exceptions.ReadTimeoutError: Read timeout on endpoint URL: "http://s3.openshift-storage.svc.cluster.local/thoth/data/thoth-test-core/thoth-sli-metrics/kebechet-update-manager/bot_knowledge/thoth-station/thoth-ops/Issue.json"
```

**Comment by pacospace** [comment]
could you add more info on how to reproduce please? what URL endpoint, what Ceph, etc..

**Comment by xtuchyna** [comment]
@pacospace yes just inspecting it rn and collecting information, will add more specification as I go on

**Comment by xtuchyna** [comment]
Hey @pacospace @harshad16 what's the status of this for the `https://s3-openshift-storage.apps.zero.massopen.cloud/` endpoint?

**Comment by goern** [comment]
what is the status of this issue?
