### ISSUE TITLE
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out.

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/mi#432]
**Describe the bug**
`mi-analysis` workflow failed due to some internal error. See LOGS for more
TBD

**LOGS**
```
INFO:srcopsmetrics.github_knowledge:Overall repositories found: 1
INFO:srcopsmetrics.bot_knowledge:######################## Analysing thoth-station/user-api ########################

INFO:srcopsmetrics.utils:No repo identified, creating new directory at /opt/app-root/src/srcopsmetrics/bot_knowledge/thoth-station/user-api
INFO:srcopsmetrics.bot_knowledge:########################
INFO:srcopsmetrics.bot_knowledge:Detected entities:
CodeFrequency # Commit # DependencyUpdate # Fork # Issue # KebechetUpdateManager # PullRequest # PullRequestDiscussion # ReadMe # Release # Stargazer
INFO:srcopsmetrics.bot_knowledge:########################
INFO:srcopsmetrics.bot_knowledge:Issue inspection
INFO:srcopsmetrics.utils:No repo identified, creating new directory at /opt/app-root/src/zero-test/mi/bot_knowledge/thoth-station/user-api
INFO:srcopsmetrics.entities.tools.storage:Loading knowledge from Ceph
INFO:srcopsmetrics.entities.interface:No previous knowledge of type Issue found
INFO:srcopsmetrics.iterator:-------------Issue Analysis-------------

  0%|          | 0/345 [00:00<?, ?it/s]
  0%|          | 1/345 [00:00<02:13,  2.58it/s]
  1%|          | 2/345 [00:00<02:37,  2.18it/s]
  1%|          | 3/345 [00:01<02:24,  2.37it/s]
  1%|          | 4/345 [00:01<02:06,  2.69it/s]
                                               
INFO:srcopsmetrics.iterator:[API requests remaining: 4203]

  1%|          | 4/345 [00:01<02:06,  2.69it/s]
  1%|â–         | 5/345 [00:01<02:04,  2.72it/s]
  2%|â–         | 6/345 [00:02<02:03,  2.75it/s]
  2%|â–         | 7/345 [00:02<02:03,  2.74it/s]
  2%|â–         | 8/345 [00:03<02:57,  1.90it/s]
  3%|â–Ž         | 9/345 [00:03<02:40,  2.10it/s]
                                               
INFO:srcopsmetrics.iterator:[API requests remaining: 4193]

  3%|â–Ž         | 9/345 [00:03<02:40,  2.10it/s]
  3%|â–Ž         | 10/345 [00:04<02:28,  2.25it/s]
  3%|â–Ž         | 11/345 [00:04<02:13,  2.50it/s]
  3%|â–Ž         | 12/345 [00:05<02:18,  2.41it/s]
  4%|â–         | 13/345 [00:05<02:21,  2.35it/s]
  4%|â–         | 14/345 [00:05<02:23,  2.31it/s]
                                                
INFO:srcopsmetrics.iterator:[API requests remaining: 4183]

  4%|â–         | 14/345 [00:05<02:23,  2.31it/s]
  4%|â–         | 15/345 [00:06<02:08,  2.58it/s]
  5%|â–         | 16/345 [00:06<02:10,  2.52it/s]
  5%|â–         | 17/345 [00:06<02:02,  2.67it/s]
  5%|â–Œ         | 18/345 [00:07<01:54,  2.85it/s]
  6%|â–Œ         | 19/345 [00:07<02:04,  2.61it/s]
                                                
INFO:srcopsmetrics.iterator:[API requests remaining: 4173]

  6%|â–Œ         | 19/345 [00:07<02:04,  2.61it/s]
  6%|â–Œ         | 20/345 [00:08<01:58,  2.74it/s]
  6%|â–Œ         | 21/345 [00:08<01:56,  2.79it/s]
  6%|â–‹         | 22/345 [00:08<01:55,  2.81it/s]
  7%|â–‹         | 23/345 [00:09<01:54,  2.81it/s]
  7%|â–‹         | 24/345 [00:09<01:51,  2.89it/s]
                                                
INFO:srcopsmetrics.iterator:[API requests remaining: 4163]

  7%|â–‹         | 24/345 [00:09<01:51,  2.89it/s]
  7%|â–‹         | 25/345 [00:09<01:49,  2.92it/s]
  8%|â–Š         | 26/345 [00:10<01:52,  2.84it/s]
  8%|â–Š         | 27/345 [00:10<01:57,  2.70it/s]
  8%|â–Š         | 28/345 [00:10<01:47,  2.94it/s]
  8%|â–Š         | 29/345 [00:11<01:43,  3.05it/s]
                                                
INFO:srcopsmetrics.iterator:[API requests remaining: 4153]

  8%|â–Š         | 29/345 [00:11<01:43,  3.05it/s]
  9%|â–Š         | 30/345 [00:11<01:43,  3.04it/s]
  9%|â–‰         | 31/345 [00:11<01:45,  2.97it/s]
  9%|â–‰         | 32/345 [00:12<01:44,  2.98it/s]
 10%|â–‰         | 33/345 [00:12<01:51,  2.81it/s]
 10%|â–‰         | 34/345 [00:12<01:53,  2.75it/s]
                                                
INFO:srcopsmetrics.iterator:[API requests remaining: 4143]

 10%|â–‰         | 34/345 [00:13<01:53,  2.75it/s]
 10%|â–ˆ         | 35/345 [00:14<03:18,  1.56it/s]
 10%|â–ˆ         | 36/345 [00:14<03:00,  1.71it/s]
 11%|â–ˆ         | 37/345 [00:14<02:39,  1.93it/s]
 11%|â–ˆ         | 38/345 [00:15<02:20,  2.18it/s]
 11%|â–ˆâ–        | 39/345 [00:15<02:08,  2.37it/s]
                                                
INFO:srcopsmetrics.iterator:[API requests remaining: 4133]

 11%|â–ˆâ–        | 39/345 [00:15<02:08,  2.37it/s]
 12%|â–ˆâ–        | 40/345 [00:15<02:00,  2.54it/s]
 12%|â–ˆâ–        | 41/345 [00:16<01:51,  2.72it/s]
 12%|â–ˆâ–        | 42/345 [00:17<02:38,  1.91it/s]
 12%|â–ˆâ–        | 43/345 [00:17<02:31,  1.99it/s]
 13%|â–ˆâ–Ž        | 44/345 [00:18<02:43,  1.84it/s]
                                                
INFO:srcopsmetrics.iterator:[API requests remaining: 4123]

 13%|â–ˆâ–Ž        | 44/345 [00:18<02:43,  1.84it/s]
 13%|â–ˆâ–Ž        | 45/345 [00:18<02:28,  2.03it/s]
 13%|â–ˆâ–Ž        | 46/345 [00:19<02:20,  2.13it/s]
 14%|â–ˆâ–Ž        | 47/345 [00:19<02:12,  2.25it/s]
 14%|â–ˆâ–        | 48/345 [00:19<01:57,  2.54it/s]
 14%|â–ˆâ–        | 49/345 [00:20<01:50,  2.67it/s]
                                                
INFO:srcopsmetrics.iterator:[API requests remaining: 4113]

 14%|â–ˆâ–        | 49/345 [00:20<01:50,  2.67it/s]
 14%|â–ˆâ–        | 50/345 [00:20<01:50,  2.66it/s]
 15%|â–ˆâ–        | 51/345 [00:20<01:45,  2.78it/s]
 15%|â–ˆâ–Œ        | 52/345 [00:21<01:44,  2.79it/s]
 15%|â–ˆâ–Œ        | 53/345 [00:21<01:37,  2.99it/s]
 16%|â–ˆâ–Œ        | 54/345 [00:21<01:32,  3.15it/s]
                                                
INFO:srcopsmetrics.iterator:[API requests remaining: 4103]

 16%|â–ˆâ–Œ        | 54/345 [00:22<01:32,  3.15it/s]
 16%|â–ˆâ–Œ        | 55/345 [00:22<02:07,  2.27it/s]
 16%|â–ˆâ–Œ        | 56/345 [00:22<02:00,  2.39it/s]
 17%|â–ˆâ–‹        | 57/345 [00:23<01:47,  2.69it/s]
 17%|â–ˆâ–‹        | 58/345 [00:23<01:43,  2.76it/s]
 17%|â–ˆâ–‹        | 59/345 [00:23<01:42,  2.79it/s]
                                                
INFO:srcopsmetrics.iterator:[API requests remaining: 4093]

 17%|â–ˆâ–‹        | 59/345 [00:23<01:42,  2.79it/s]
 17%|â–ˆâ–‹        | 60/345 [00:23<01:34,  3.02it/s]
 18%|â–ˆâ–Š        | 61/345 [00:24<01:41,  2.81it/s]
 18%|â–ˆâ–Š        | 62/345 [00:24<01:37,  2.89it/s]
 18%|â–ˆâ–Š        | 63/345 [00:24<01:32,  3.05it/s]
 19%|â–ˆâ–Š        | 64/345 [00:25<01:26,  3.24it/s]
                                                
INFO:srcopsmetrics.iterator:[API requests remaining: 4083]

 19%|â–ˆâ–Š        | 64/345 [00:25<01:26,  3.24it/s]
 19%|â–ˆâ–‰        | 65/345 [00:25<01:24,  3.30it/s]
 19%|â–ˆâ–‰        | 66/345 [00:25<01:28,  3.15it/s]
 19%|â–ˆâ–‰        | 67/345 [00:26<01:32,  2.99it/s]
 20%|â–ˆâ–‰        | 68/345 [00:26<01:28,  3.14it/s]
 20%|â–ˆâ–ˆ        | 69/345 [00:26<01:26,  3.21it/s]
                                                
INFO:srcopsmetrics.iterator:[API requests remaining: 4073]

 20%|â–ˆâ–ˆ        | 69/345 [00:26<01:26,  3.21it/s]
 20%|â–ˆâ–ˆ        | 70/345 [00:27<01:25,  3.23it/s]
 21%|â–ˆâ–ˆ        | 71/345 [00:27<01:20,  3.39it/s]
 21%|â–ˆâ–ˆ        | 72/345 [00:27<01:17,  3.51it/s]
 21%|â–ˆâ–ˆ        | 73/345 [00:27<01:20,  3.37it/s]
 21%|â–ˆâ–ˆâ–       | 74/345 [00:28<01:19,  3.43it/s]INFO:srcopsmetrics.iterator:[API requests remaining: 4063]

                                                

 21%|â–ˆâ–ˆâ–       | 74/345 [00:28<01:19,  3.43it/s]
 22%|â–ˆâ–ˆâ–       | 75/345 [00:28<01:22,  3.26it/s]
 22%|â–ˆâ–ˆâ–       | 76/345 [00:29<01:33,  2.86it/s]
 22%|â–ˆâ–ˆâ–       | 77/345 [00:29<01:36,  2.77it/s]
 23%|â–ˆâ–ˆâ–Ž       | 78/345 [00:29<01:31,  2.93it/s]
 23%|â–ˆâ–ˆâ–Ž       | 79/345 [00:30<01:33,  2.85it/s]
                                                
INFO:srcopsmetrics.iterator:[API requests remaining: 4053]

 23%|â–ˆâ–ˆâ–Ž       | 79/345 [00:30<01:33,  2.85it/s]
 23%|â–ˆâ–ˆâ–Ž       | 80/345 [00:30<01:29,  2.96it/s]
 23%|â–ˆâ–ˆâ–Ž       | 81/345 [00:30<01:31,  2.90it/s]
 24%|â–ˆâ–ˆâ–       | 82/345 [00:31<01:30,  2.91it/s]
 24%|â–ˆâ–ˆâ–       | 83/345 [00:31<01:34,  2.78it/s]
 24%|â–ˆâ–ˆâ–       | 84/345 [00:31<01:29,  2.91it/s]
                                                
INFO:srcopsmetrics.iterator:[API requests remaining: 4043]

 24%|â–ˆâ–ˆâ–       | 84/345 [00:31<01:29,  2.91it/s]
 25%|â–ˆâ–ˆâ–       | 85/345 [00:32<01:33,  2.77it/s]
 25%|â–ˆâ–ˆâ–       | 86/345 [00:32<01:35,  2.71it/s]
 25%|â–ˆâ–ˆâ–Œ       | 87/345 [00:33<01:39,  2.59it/s]
 26%|â–ˆâ–ˆâ–Œ       | 88/345 [00:33<01:41,  2.53it/s]
 26%|â–ˆâ–ˆâ–Œ       | 89/345 [00:33<01:37,  2.61it/s]
                                                
INFO:srcopsmetrics.iterator:[API requests remaining: 4033]

 26%|â–ˆâ–ˆâ–Œ       | 89/345 [00:33<01:37,  2.61it/s]
 26%|â–ˆâ–ˆâ–Œ       | 90/345 [00:34<01:41,  2.52it/s]
 26%|â–ˆâ–ˆâ–‹       | 91/345 [00:34<01:32,  2.74it/s]
 27%|â–ˆâ–ˆâ–‹       | 92/345 [00:34<01:25,  2.97it/s]
 27%|â–ˆâ–ˆâ–‹       | 93/345 [00:35<01:21,  3.08it/s]
 27%|â–ˆâ–ˆâ–‹       | 94/345 [00:35<01:33,  2.68it/s]
                                                
INFO:srcopsmetrics.iterator:[API requests remaining: 4023]

 27%|â–ˆâ–ˆâ–‹       | 94/345 [00:35<01:33,  2.68it/s]
 28%|â–ˆâ–ˆâ–Š       | 95/345 [00:36<01:36,  2.60it/s]
 28%|â–ˆâ–ˆâ–Š       | 96/345 [00:36<01:34,  2.62it/s]
 28%|â–ˆâ–ˆâ–Š       | 96/345 [00:51<02:13,  1.87it/s]
INFO:srcopsmetrics.iterator:Cached knowledge could not be saved
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/app-root/lib64/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.8/http/client.py", line 1332, in getresponse
    response.begin()
  File "/usr/lib64/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib64/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib64/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/app-root/lib64/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/opt/app-root/lib64/python3.8/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/app-root/lib64/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/opt/app-root/lib64/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/app-root/lib64/python3.8/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/opt/app-root/lib64/python3.8/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=15)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "srcopsmetrics/cli.py", line 196, in <module>
    cli(auto_envvar_prefix="MI")
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "srcopsmetrics/cli.py", line 159, in cli
    analyse_projects(projects=tupled_repos, is_local=is_local, entities=entities_args)
  File "/opt/app-root/src/srcopsmetrics/bot_knowledge.py", line 91, in analyse_projects
    github_knowledge.analyse_entity(
  File "/opt/app-root/src/srcopsmetrics/github_knowledge.py", line 187, in analyse_entity
    analysis.run()
  File "/opt/app-root/src/srcopsmetrics/iterator.py", line 90, in run
    remaining = self.github.get_rate_limit().core.remaining
  File "/opt/app-root/lib64/python3.8/site-packages/github/MainClass.py", line 201, in get_rate_limit
    headers, data = self.__requester.requestJsonAndCheck("GET", "/rate_limit")
  File "/opt/app-root/lib64/python3.8/site-packages/github/Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
  File "/opt/app-root/lib64/python3.8/site-packages/github/Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/opt/app-root/lib64/python3.8/site-packages/github/Requester.py", line 528, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/opt/app-root/lib64/python3.8/site-packages/github/Requester.py", line 555, in __requestRaw
    response = cnx.getresponse()
  File "/opt/app-root/lib64/python3.8/site-packages/github/Requester.py", line 127, in getresponse
    r = verb(
  File "/opt/app-root/lib64/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=15)

```

**Comment by xtuchyna** [comment]
Could not be reproducible anymore. Leaving it closed
