### ISSUE TITLE
thoth metrics `AssertionError: Repository(full_name="thoth-station/s2i-python-container")`

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/mi#552]
## Bug description
When using `-t` option on `thoth-station/s2i-python-container` repo, `Assertion` error occurs

### Expected behavior
`AssertionError` should not occur within code

### LOGS
```
INFO:aicoe-src-ops-metrics:#### Launching thoth data analysis ####
INFO:aicoe-src-ops-metrics:Creating metrics for repository thoth-station/s2i-python-container
Traceback (most recent call last):
  File "srcopsmetrics/cli.py", line 219, in <module>
    cli(auto_envvar_prefix="MI")
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "srcopsmetrics/cli.py", line 191, in cli
    kebechet_metrics = KebechetMetrics(repository=repo, day=yesterday, is_local=is_local)
  File "/opt/app-root/src/srcopsmetrics/kebechet_metrics.py", line 70, in __init__
    self.prs = PullRequest(gh_repo).load_previous_knowledge(is_local=is_local)
  File "/opt/app-root/src/srcopsmetrics/entities/interface.py", line 59, in __init__
    self.repository = github_handling.connect_to_source(repository_name)
  File "/opt/app-root/src/srcopsmetrics/github_handling.py", line 92, in _wrapper
    return original_funcion(*args, **kwargs)
  File "/opt/app-root/src/srcopsmetrics/github_handling.py", line 109, in connect_to_source
    return get_github_object().get_repo(repository_name)
  File "/opt/app-root/lib64/python3.8/site-packages/github/MainClass.py", line 323, in get_repo
    assert isinstance(full_name_or_id, (str, int)), full_name_or_id
AssertionError: Repository(full_name="thoth-station/s2i-python-container")

```

**Comment by goern** [comment]
is this still relevant?
